parameters:
    acme_notifyconnector.connector_name.csv: 'Acme CSV Notify Connector'
    acme_notifyconnector.job_name.csv_product_export_notify: 'csv_product_export_notify'

services:
    #-----------------------------------------------------------------
    # Jobs
    #-----------------------------------------------------------------
#    acme_notifyconnector.csv_product_export_notify:
    acme_notifyconnector.job.csv_product_export_notify:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%acme_notifyconnector.job_name.csv_product_export_notify%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@pim_connector.step.csv_product.export'
                - '@acme_notifyconnector.step.notify'
        tags:
            - { name: akeneo_batch.job, connector: '%acme_notifyconnector.connector_name.csv%', type: '%pim_connector.job.export_type%' }

    #-----------------------------------------------------------------
    # Steps
    #-----------------------------------------------------------------
    acme_notifyconnector.step.notify:
        class: 'Acme\Bundle\NotifyConnectorBundle\Step\NotifyStep'
        arguments:
            - 'notify'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'